### ISSUE TITLE
テーブルの構造確認

### ISSUE THREAD

**Issue by i3NakashimaTakumi** [i3design-training/backend-library-app#79]
```json
{
  "books": {
    "B1": {
      "title": "リーダブルコード",
      "authors": ["aaa", "sss"],
      "imageLinks": { "thumbnail": "aaa", "smallThumbnail": "eee" },
      "publisher": "aaa",
      "publishedDate": "2024-01-01",
      "pageCount": 333,
      "description": "aaaaaaa",
      "category": "エンジニア",
      "tags": ["PHP", "Laravel"],
      "stock": 2,
      "borrowers": [
        {"name": "aaa", "email": "aaa@aa.co.jp", "returnDate": "2024-06-06"},
        {"name": "eee", "email": "eee@aa.co.jp", "returnDate": "2024-06-07"}
      ],
      "lentCount": "0",
      "createDate": "2024-01-01",
      "updateDate": "2024-01-02"
    }
  },

  "users": {
    "aaa@i3design.co.jp": {
      "password": "pass",
      "name": "中島",
      "iconPath": "hafhafajaigaagjjrajl",
      "auth": true,
      "lentingBooks": ["B1"],
      "record": [
        {
          "bookId": "B1",
          "checkoutDate": "2024-06-01"
        }
      ]
    }
  },

  "categories": [
    { "category": "エンジニア", "tags": ["PHP", "Laravel"] },
    { "category": "デザイン", "tags": ["figma"] }
  ]
}
```

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
authは管理者を指してますか？adminの方がいいかと思いました。
```
"users": {
    "aaa@i3design.co.jp": {
      "auth": true,
```

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
借りているもの？過去に借りた本の履歴どちらを指してますか？
```
"record": [
        {
          "bookId": "B1",
          "checkoutDate": "2024-06-01"
        }
      ]
```

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
categoryは1つしか紐づかないですか？B1は何を指してますか？
```
  "books": {
    "B1": {
      "category": "エンジニア",
    }
  },
```

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
パーティションキー、ソートキー決まっていれば教えて欲しいです。

**Comment by i3NakashimaTakumi** [comment]
> @i3NakashimaTakumi authは管理者を指してますか？adminの方がいいかと思いました。
> 
> ```
> "users": {
>     "aaa@i3design.co.jp": {
>       "auth": true,
> ```

管理者かどうかを指しているのでadminに変更します

**Comment by i3NakashimaTakumi** [comment]
> @i3NakashimaTakumi categoryは1つしか紐づかないですか？B1は何を指してますか？
> 
> ```
>   "books": {
>     "B1": {
>       "category": "エンジニア",
>     }
>   },
> ```

categoryは1つしか結びつかない想定です。
B1は本を一意に判別するidのつもりです。

**Comment by i3NakashimaTakumi** [comment]
> @i3NakashimaTakumi パーティションキー、ソートキー決まっていれば教えて欲しいです。

パーティションキー、ソートキーはまだ決まっていないです。
そもそもこれらのキーの概念がよくわかっていないので教えていただけると嬉しいです。

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
> 過去に借りた本の履歴を指しています。
本を借りるたびに追加していく想定です。

無限に増えていくのでしょうか...？過去何件までの制限や過去何ヶ月までのような制限があった方がいいと思いました。
DynamoDBの読み取りは8KBで1単位(正確には違ったらすみません。)です。単位量によって請求されてしまうので無限に増えていくと将来の読み取りリクエストの請求額が大きくなってしまう恐れがあります。

> B1は本を一意に判別するidのつもりです。

一つのテーブルにbooks, users, categoriesを登録する予定ですかね？

**Comment by i3NakashimaTakumi** [comment]
> @i3NakashimaTakumi
> 
> > 過去に借りた本の履歴を指しています。
> > 本を借りるたびに追加していく想定です。
> 
> 無限に増えていくのでしょうか...？過去何件までの制限や過去何ヶ月までのような制限があった方がいいと思いました。 DynamoDBの読み取りは8KBで1単位(正確には違ったらすみません。)です。単位量によって請求されてしまうので無限に増えていくと将来の読み取りリクエストの請求額が大きくなってしまう恐れがあります。
> 

制限はチーム内とクライアントの両方で話し合って決めておきたいと思います。

> > B1は本を一意に判別するidのつもりです。
> 
> 一つのテーブルにbooks, users, categoriesを登録する予定ですかね？

一応その予定ではいました。シングルテーブルじゃない方がいいというのであれば変更でもいいと思いますが、
リレーショナルデータベースでないためクエリが増えてしまうのかなと感じていました。
正直NoSQLを触ったことがないのでどういう構造がいいのかはわかってないです。

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
パーションキーはプライマリキーになり重複した値を持てなくなります。ただ複合プライマリキーにすることもできて、これはパーティションキーとソートキーの組み合わせで決まります。複合プライマリキーの場合は、パーテションキーに同じ値を設定することが可能になります。

↓ここ読んでみてください
https://aws.amazon.com/jp/builders-flash/202404/learn-dynamodb-primary-key/
https://qiita.com/shibataka000/items/e3f3792201d6fcc397fd

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
> 一応その予定ではいました。シングルテーブルじゃない方がいいというのであれば変更でもいいと思いますが、
リレーショナルデータベースでないためクエリが増えてしまうのかなと感じていました。
正直NoSQLを触ったことがないのでどういう構造がいいのかはわかってないです。

設計の面では僕も経験があるわけではないのですが、、、scanすると余計なデータも取ってくることになってしまうので毎回必ずfilterかける必要が出てしまうと思います。それと何をキーにするかが難しい気もしますが、それでもよければこのままの構造でもいいと思います。テーブルの分けるのは管理が楽かなと思ってのことです。

**Comment by m-akira0924** [comment]
RDBに変更
https://docs.google.com/spreadsheets/d/1T-mGjTcKETOOfe9JHc0IQh3-CWsdmsGLaofhWWy6oWM/preview?usp=sharing

**Comment by m-akira0924** [comment]
確認
・books-tagsが多対多
・ユーザーの借りた書籍の履歴はis_borrowingは判断（論理削除）

指摘事項
・NULLABLE追加 -Done
・varchar(16)足りないかも -Done
・カテゴリ検索もあるので、categoriesのマスタテーブルは残して、booksテーブルにcategoryIDを追加 -Done

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
- is_borrowingのdefault値はfalse
- `book_id`より`book_isbn`の方がいい気がした。
- 出版日や概要など、APIから取ってきたデータに必ずあるか怪しいのでNOT NULLは良くないかも

指摘被ってたらすみません。🙏

**Comment by i3NakashimaTakumi** [comment]
- is_borrowingのdefault値falseに変更しておきました
- isbnだと10と13の2種類あるのでどうなのかなと思いGoogleBooksAPIからそのままidというカラム名にしていました
- 出版日や概要などはないかどうか判定して、ない場合は何かしらの値を入れようと考えていました
（例：出版日：不明、概要：書籍登録者に軽くどんな本か記述してもらうなど）。
  それでもまずそうなカラムがあったら指摘お願いします！

**Comment by i3NakashimaTakumi** [comment]
> * 出版日や概要などはないかどうか判定して、ない場合は何かしらの値を入れようと考えていました
>   （例：出版日：不明、概要：書籍登録者に軽くどんな本か記述してもらうなど）。

そもそもこのやり方がまずそうだったらその点についても指摘お願いします🙏

**Comment by natsuki-07** [comment]
@i3NakashimaTakumi 
> 出版日や概要などはないかどうか判定して、ない場合は何かしらの値を入れようと考えていました

空欄を許容するか登録者の手間を取るかの差なのかなと思うのでお任せします。
どうやって登録するかあまりわかっていないけど、管理者もデフォルトはfalseがいいかな
あとは僕の方からは特に問題ないかと、そんなにDB設計詳しくないので、、、

**Comment by i3NakashimaTakumi** [comment]
@natsuki-07 

> > 出版日や概要などはないかどうか判定して、ない場合は何かしらの値を入れようと考えていました
> 
> 空欄を許容するか登録者の手間を取るかの差なのかなと思うのでお任せします。 
了解です、その辺りはチームで話し合って決めようと思います。

管理者はアカウント登録時に強制で指定しないといけないので大丈夫だとは思いますが、デフォルトfalseに変更しておきます！

**Comment by i3NakashimaTakumi** [comment]
お二人とも問題なさそうということなので、Closeしようと思います！
もし何かあったらSlack等で連絡いただけると嬉しいです！
